base_url = "https://waiyan13.com"
title = "waiyan13"
build_search_index = true
generate_feeds = true
compile_sass = true
minify_html = true
taxonomies = [{ name = "tags" }]

theme = "apollo"

[search]
include_title = true
include_description = true
include_path = true
include_content = true
index_format = "elasticlunr_json"

[markdown.highlighting]
style = "class"
light_theme = "ayu-light"
dark_theme = "ayu-dark"
error_on_missing_language = true

[extra]
toc = true
use_cdn = false
favicon = "/icon/favicon.png"
theme = "toggle"              # light, dark, auto, toggle
fancy_code = true
dynamic_note = true           # a note that can be toggled
repo_url = "https://github.com/waiyan13/waiyan13.com/blob/main/content/"

menu = [
    { name = "/blog", url = "/blog", weight = 1 },
    { name = "/projects", url = "/projects", weight = 2 },
]

socials = [
    { name = "linkedin", url = "https://www.linkedin.com/in/waiyan13", icon = "linkedin" },
    { name = "github", url = "https://github.com/waiyan13/", icon = "github" },
]

stylesheets = [
    # "custom.css"    # at /static/custom.css
]

[extra.analytics]
enabled = false

